### ISSUE TITLE
bad installation instructions, use 'gem "turbo-router"' instead

### ISSUE THREAD

**Issue by odysseyjason** [WriterZephos/turbo-router#1]
Your readme instructs to install via

gem "turbo_router" 

but this gem is not found, it can be installed by

**gem "tubro-router"** instead.

**Comment by WriterZephos** [comment]
This seems weird to me. The gem is published here: https://rubygems.org/gems/turbo-router

I will look into it. I published this a year ago and haven't worked on it since, so it's due for a refresh. Thanks for actually taking an interest! I was wondering if anyone would ever try using it.

**Comment by odysseyjason** [comment]
Yes, it is just the instructions here on github Readme file that are wrong, and I guessed as much and figured it out.

**Comment by WriterZephos** [comment]
Oh okay I will update them.

**Comment by WriterZephos** [comment]
Should be fixed now. New version is 0.1.3
