### ISSUE TITLE
current package is missing file called in generator

### ISSUE THREAD

**Issue by odysseyjason** [WriterZephos/turbo-router#2]
rails generate turbo_router
      create  app/views/layouts/_turbo_router_content.erb
      create  app/views/layouts/turbo_router_content.erb
Could not find "turbo_router_stream.erb" in any of your source paths. Your current source paths are:
/home/odyex/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/turbo-router-0.1.2/lib/generators/templates

The file is in previous versions on this repository

**Comment by WriterZephos** [comment]
I will take a look at this tonight. Thank you!

**Comment by WriterZephos** [comment]
Should be fixed now. Let me know! New version is 0.1.3
